# Generated by Django 4.2 on 2023-05-24 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_book_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolio.book'),
        ),
    ]
